export const METRICS_GUID = '94187e3f-9890-4855-9d47-1415a650589f';
export const API_URL = 'http://88.198.64.26:5000';

export const CHANGE_PAGE_REQUEST = 'CHANGE_PAGE_REQUEST';

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST';

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST';
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS';

export const DRAGGABLE_BLOCK = 'DRAGGABLE_BLOCK';

export const GET_PAGES_REQUEST = 'GET_PAGES_REQUEST';
export const GET_PAGES_SUCCESS = 'GET_PAGES_SUCCESS';

export const FOCUS_BLOCK = 'FOCUS_BLOCK';

export const CHANGE_PAGE_TITLE_REQUEST = 'CHANGE_PAGE_TITLE_REQUEST';
export const CHANGE_PAGE_TITLE_SUCCESS = 'CHANGE_PAGE_TITLE_SUCCESS';

export const INITIAL_PAGE = {
    title: 'Untitled',
    content: [{ data: '' }]
}